/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as functionGuzzlerSol from "./FunctionGuzzler.sol";
export type { functionGuzzlerSol };
import type * as stakingContractSol from "./StakingContract.sol";
export type { stakingContractSol };
import type * as stakingContractOpSol from "./StakingContractOP.sol";
export type { stakingContractOpSol };
export type { FunctionGuzzlerOP } from "./FunctionGuzzlerOP";
export type { StandardERC20 } from "./StandardERC20";
export type { StandardERC20_OP } from "./StandardERC20_OP";
