/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { FunctionGuzzler } from "./FunctionGuzzler";
export type { IFunctionGuzzler } from "./IFunctionGuzzler";
